name: Nueva Norway
favicon: null
layout_spectrum: 0.567781409015879
typography_spectrum: 0.31260695145465434
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.45701743266545236
  lightness: 0.08432558784261346
  saturation: 0.41657500294968486
  rhythmicContrast: 0.6890917257405818
purpose: []
